[build]
  command = "npm run build -- --configuration=production --base-href=/"
  publish = "dist/CineVerse/browser"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
